# Generated by Django 2.2.17 on 2020-11-17 05:33

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FullUserData',
            fields=[
                ('email', models.EmailField(max_length=100, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=100)),
                ('full_name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('college', models.CharField(max_length=100)),
                ('experience', models.CharField(max_length=30)),
                ('passout', models.IntegerField(default=2020)),
                ('relocation', models.CharField(max_length=30)),
                ('find_us', models.CharField(max_length=50)),
                ('ref_id', models.CharField(max_length=50, null=True)),
                ('mobile_no', models.CharField(max_length=12, null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('resume_link', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='InternData',
            fields=[
                ('intern_id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.FullUserData')),
            ],
        ),
        migrations.CreateModel(
            name='WorkData',
            fields=[
                ('intern_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='home.InternData')),
                ('date', models.DateField(default=datetime.date.today)),
                ('no_enrolled', models.IntegerField(default=0)),
            ],
        ),
    ]
