# Generated by Django 2.2.17 on 2020-11-17 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fulluserdata',
            name='payment',
            field=models.CharField(default='No', max_length=3),
        ),
    ]
