# Generated by Django 2.2.3 on 2019-12-10 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20191210_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='desc',
            field=models.CharField(max_length=160),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='topic',
            field=models.CharField(max_length=100),
        ),
    ]
