# Generated by Django 2.2.3 on 2019-12-23 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20191210_1013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='subject',
        ),
    ]
