# Generated by Django 2.2.17 on 2020-11-17 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_payments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workdata',
            name='intern_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
