# Generated by Django 2.2.17 on 2020-11-17 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20201117_1226'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WorkData',
        ),
    ]
