# Generated by Django 2.2.17 on 2020-11-17 12:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_delete_workdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intern_id', models.IntegerField(default=10000)),
                ('date', models.DateField(default=datetime.date.today)),
                ('no_enrolled', models.IntegerField(default=0)),
            ],
        ),
    ]
