# Generated by Django 2.2.17 on 2020-11-17 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_workdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='fulluserdata',
            name='option',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='interndata',
            name='target',
            field=models.IntegerField(default=132),
        ),
    ]
