# Generated by Django 2.2.17 on 2020-11-17 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20201117_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='workdata',
            name='out_enrolls',
            field=models.IntegerField(default=1),
        ),
    ]
