# Generated by Django 2.2.17 on 2020-11-17 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_workdata_out_enrolls'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workdata',
            old_name='out_enrolls',
            new_name='out_enrolled',
        ),
    ]
